### ISSUE TITLE
Add multidimensional capabilities to SN

### ISSUE THREAD

**Issue by myerspat** [myerspat/tt_nte#2]
## Background

We need to accommodate 2D and 3D geometries in `tt_nte.methods.DiscreteOrdinates`.  The current path forward will not work for convex geometries.

## Tasks

- [x] Refactor `tt_nte.geometry.Geometry` to utilize gmsh for meshing
  - [x] Support current 1D capabilities as well as 2D and 3D geometries (assuming non-convex regions)
- [ ] Refactor `tt_nte.methods.DiscreteOrdinates` for 2D and 3D support
  - [ ] Implement square quadrature set for arbitrary number of ordinates
  - [ ] Upgrade `tt_nte.methods.DiscreteOrdinates._construct_tensor_trains()` to utilize the full capabilities of `tt_nte.geometry.Geometry` includeing:
    - [ ] Build the streaming TTs depending on the requested 1/2/3D geometry
    - [ ] Upgrade scattering moments to use spherical harmonics for 2D and 3D
    - [ ] Add additional spatial cores to each operator for higher dimensional geometry while utilizing masks for multi-region
    - [ ] Iterate over all quadrants/octants using appropriate boundary conditions

## Definition of Done

- [ ] 2D representation of the multi-region benchmark converges to 1 for increasing the number of ordinates and mesh resolution.
- [ ] Possibly include Jezebel benchmark developed in https://www.sciencedirect.com/science/article/pii/S002199912400192X?ref=pdf_download&fr=RR-2&rr=89a552761c9a32c2#br0410
