### ISSUE TITLE
Simple Benchmark for testing TT methods

### ISSUE THREAD

**Issue by myerspat** [myerspat/tt_nte#4]
## Background

We need benchmark solutions to ensure our TT methods produce reliable results. This first benchmark will be based on the OpenMC notebook found at [https://docs.openmc.org/en/v0.12.2/examples/mg-mode-part-ii.html](https://docs.openmc.org/en/v0.12.2/examples/mg-mode-part-ii.html).

## Tasks

I want four sets of solutions for a $63\times 63$, $127\times 127$, $255\times 255$, and $511\times 511$ regular mesh. This is the mesh size, meaning there are $n\times n$ cells; therefore, there are $(n + 1)\times(n + 1)$ nodes which TT will solve for. Create the following:
- [ ] Multigroup cross sections (XSs) with isotropic scattering ($L = 0$) at each cell center location. Note that you should generate the following XS files as numpy binaries (`.npy`):
  - [ ] total
  - [ ] absorption
  - [ ] nu-fission,
  - [ ] fission,
  - [ ] scatter.
  Note that each XS should be shaped (groups, $n$, $n$).
- [ ] Generate a global average for the fission spectrum (chi), thus making it a vector of length groups. You can use the `openmc.mgxs` module to build the tally for this and save it. It should be saved as a CSV in their MGXS format. 
- [ ] Save the representative eigenvalue $k$ and cell scalar flux $\phi$ solutions. Therefore, the eigenvalue will be a scalar that you can get from either the OpenMC run's printed output or the statepoint file. You can save the scalar flux the same way as the XSs, and it should be shaped (groups, $n$, $n$).

Place the XSs and generation scripts within a directory called `benchmarks/openmc/assembly/` under `scripts/`. Ensure the results for each level of discretization is saved in a subdirectory called `nxn/` where n is the discretization for that run. Therefore, for the XSs, scalar flux, chi, and eigenvalue of the $63\times 63$ case, place them in `scripts/benchmarks/openmc/assembly/63x63/`. 

## Definition of Done

You include the four sets of solutions with the relevant data to compare the Monte Carlo (MC) solution and the TT discrete ordinates solution.
